Lexplorer/Components/OrderbookTradeTransactionDetail.razor, Lexplorer/Components/SwapTransactionDetail.razor, Lexplorer/Components/TransactionTableDetails.razor, Lexplorer/Components/TransferTransactionDetail.razor, Lexplorer/Helpers/AccountLinkHelper.cs, Lexplorer/Helpers/GraphQLFragments.cs, Lexplorer/Models/OrderbookTrade.cs, Lexplorer/Models/Swap.cs, Lexplorer/Models/Transactions.cs, Lexplorer/Models/Transfer.cs, Lexplorer/Pages/Account.razor, Lexplorer/Services/GraphQLService.cs, Lexplorer/Shared/NavMenu.razor
Hey there - I tried to extend Lexplorer with an accounts page showing transactions of the account. Please bear with me as this is my first foray into Blazor!
There's still a lot to be done, like adding the balances, but the PR is fairly large already.
=> Adding an accounts page and linking to it

Lexplorer/Pages/NFTDetail.razor, Shared/Models/NftMetadata.cs, Shared/Services/LoopringGraphQLService.cs
fix #71. add support for non ipfs image link
=> modified nft metadata to allow for non ipfs nft image link

Lexplorer/Shared/MainLayout.razor, Shared/Services/LoopringGraphQLService.cs, xUnitTests/LoopringGraphTests/TestSearch.cs
* combined everything into one query using aliases
* support for searching NFTs via nftID or complete ID
* 0x is now optional when searching
* managing a separate searchTermBytes with strict regex matching to avoid query errors
* improved search GUI, clearing when switching to a different page etc.
=> search improvements

Lexplorer/Components/NFTContent.razor, Lexplorer/Pages/NFTDetail.razor
I've tried to simplify the new code a bit and separated a new NFTContent razor component.
Unfortunately I ended up not using it for NFTs on the accounts page as it broke the layout with its fixed width/height approach.
I also tried to make the NFT grid on the accounts page look better, but I'm clueless about CSS and flex and whatever so I gave up and will create an issue.
=> Refactor nft details

Lexplorer/Pages/Account.razor
=> Switch local NFTData dict to NFT.id since nftID is not unique it seems

Lexplorer/Pages/BlockDetails.razor, Lexplorer/Pages/BlocksOverview.razor, Shared/Services/LoopringGraphQLService.cs
* adapt layout for pagination etc.
* add cancellation token to block detail
* make pages null safe using ? operator
=> Modernize block pages

Shared/Services/TransactionExportCointracking.cs, Shared/Services/TransactionExportDefaultCSVFormat.cs
Most important was changing transaction type names so CoinTracking.info does actually import the CSV.
Also added MintNFT and WithdrawalNFT.
=> Some smaller export improvements

Lexplorer/Pages/AccountsOverview.razor, Shared/Services/LoopringGraphQLService.cs, xUnitTests/LoopringGraphTests/TestAccount.cs
* similar to transactions overview
* type filtering (implemented via redirecting the query to the correct
entity)
* added new method to service, 2 simple test cases
=> Added account overview page

Lexplorer/Components/HomepageOverview.razor, Lexplorer/Lexplorer.csproj, Lexplorer/Pages/Account.razor, Lexplorer/Pages/_Layout.cshtml, Lexplorer/Shared/MainLayout.razor, Lexplorer/wwwroot/app.css, Shared/Services/LoopringGraphQLService.cs
* Fixed showing of NFT's on account detail page. 
* Fixed appname in appbar to be hidden on small devices. 
* Fixed card sizes and breakpoints on overview page.
=> Fix: Mobile friendlyness

Lexplorer/Components/HomepageOverview.razor, Lexplorer/Components/L1AccountLink.razor, Lexplorer/Components/L1TransactionLink.razor, Lexplorer/Components/PairsTableDetails.razor, Lexplorer/Helpers/LinkHelper.cs, Lexplorer/Lexplorer.csproj, Lexplorer/Pages/PairsDetail.razor, Lexplorer/Pages/PairsOverview.razor, Lexplorer/Pages/_Layout.cshtml, Lexplorer/Shared/MainLayout.razor, Shared/Models/LoopringV3.cs, Shared/Services/LoopringGraphQLService.cs, xUnitTests/LoopringGraphTests/TestPairs.cs
This took forever, but finally I think I've reached a stage that is good enough for a first merge. Of course there's still lots of room for improvement.
@danielsolistensvik and @fudgebucket27 I'd appreciate if you could have a thorough look at this.
One thing that I'm not satisfied with is the height of the chart. I've specified nothing for now, but my impression is, it's too much on a large display and too little everywhere else. @danielsolistensvik after you improved the accounts page so much, what's your take on this?
=> New Pairs details page with ApexCharts

Lexplorer/Components/HomepageOverview.razor, Lexplorer/Shared/MainLayout.razor
* New ordering of tables on homepage overview. 
* New breakpoint for drawer, now set to large.
=> Fix: Ordering of tables

Lexplorer/Pages/PairsDetail.razor
* volume now shown in Token1, because Token0Price is in Token1 too
* added titles making more clear what is shown
=> Make charts more consistent

Lexplorer/Components/HomepageOverview.razor
* join the 3 grids into one
* replace the sm breakpoint (same as xs) with new md = 6 for 2 cols
* fixes #155
=> Fix #155 medium size home page with 2 cards per row

Lexplorer/Components/TransactionTableDetails.razor
* copy/paste error, now using withdrawal instead of deposit = null
=> Transaction table for withdrawal was missing token symbol

Lexplorer/Lexplorer.csproj, Lexplorer/Pages/AccountDetails.razor, Shared/Services/LoopringGraphQLService.cs, xUnitTests/LoopringGraphTests/TestNFT.cs
* Added MudPager for nft pagination
* Added method in LoopringGraphService to get total number of nftslots for account
=> Feature: New nft pager

Lexplorer/Components/TransactionTableDetails.razor, Lexplorer/Pages/TransactionDetail.razor, Shared/Helpers/GraphQLFragments.cs, Shared/Models/LoopringV3.cs
Fixes #188 
* NFTAmountSold property getter distinguishing whether A is selling
the NFT (token > 32767)
=> Fix NFT trade display

Lexplorer/Pages/NFTDetail.razor, Shared/Models/NftMetadata.cs, Shared/Services/NftMetadataService.cs
* similar but not necessarily identical to traits
* each displayed in an expandable section
=> Add NFT properties

Lexplorer/Components/TransactionTableDetails.razor, Lexplorer/Helpers/LinkHelper.cs, Lexplorer/Pages/TransactionDetail.razor, Shared/Helpers/GraphQLFragments.cs, Shared/Helpers/GraphQLTransactionListFragments.cs, Shared/Models/LoopringV3.cs, Shared/Services/LoopringGraphQLService.cs, xUnitTests/LoopringGraphTests/TestNFT.cs
Fixes #208 
* extended transaction list fragments and queries
* added DataNFT class (back) to model
* extended normal fragment with relevant info
Overview:
Details:
=> Add support for DataNFT transactions

Lexplorer/Pages/NFTDetail.razor, Shared/Models/NftMetadata.cs, Shared/Services/NftMetadataService.cs, xUnitTests/NFTMetaDataTests/TestNFTMetaData.cs
Closes #220 
Full description at the linked issue.
=> Show NFT meta data problems and fix unescaped links

Lexplorer/Pages/NFTDetail.razor
Closes #234 
* as it's very similar to token holders
=> Fix #234: Add ENS names to NFT holder table

Lexplorer/Shared/MainLayout.razor, Shared/Services/ENSCacheService.cs
Fixes #240
Also prevents search for empty string (rare use-case)
=> Fix ENS lookup being case sensitive

Shared/Services/TransactionExportDefaultCSVFormat.cs
adds missing tradenft transaction type to the export csv
=> adds tradenft transaction type to export csv

Lexplorer/Pages/PairsDetail.razor, Shared/Models/LoopringV3.cs, Shared/Services/LoopringGraphQLService.cs
* added a 2nd set of charts for weekly data
* turned both sets into expansion panels
=> Added weekly charts and expansion panels
