fudgebucket27/Lexplorer

- Lexplorer/Helpers/GraphQLFragments.cs
- Lexplorer/Models/LoopringV3.cs
- Lexplorer/Pages/Account.razor
- Lexplorer/Services/GraphQLService.cs
* removed balances from PoolFragment - not used AFAICs
** the balances of each account are retrieved in a separate query,
see GetAccountBalance
* added specific fields and createdAtTransaction to User and Pool
fragments
** used a separate more limited fragment for createdAtTransaction to
avoid recurcsion like Pool.createdAtTransaction.block.operator
** added fragment to all queries which had Pool and UserFragments
* as this whole episode caused lots of troubles with malformed queries,
hardened code in GraphQLService so exceptions are caught and logged
> extend Accounts page with CreatedAt and PublicKey for Users

- Lexplorer/Components/DepositTransactionDetail.razor
- Lexplorer/Components/HomepageOverview.razor
- Lexplorer/Components/OrderbookTradeTransactionDetail.razor
- Lexplorer/Components/SwapTransactionDetail.razor
- Lexplorer/Components/TransactionTableDetails.razor
- Lexplorer/Components/TransferTransactionDetail.razor
- Lexplorer/Helpers/LinkHelper.cs
- Shared/Models/LoopringV3.cs
- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/TestPairs.cs
- xUnitTests/LoopringGraphTests/TestSearch.cs
1. Implementing search (closing issue #46)
1. only block, account and transaction IDs for now
2. combined query for all, returning one list of object
3. renamed, extended LinkHelper
2. Improvement homepage in general
1. made it null safe with progress indicators while loading
2. now using ? not ! as actually the former is null-safe, the latter will raise an exception
3. proxy info no longer queried with transactions *and* blocks but just blocks
5. better string formats for larger numbers
6. Pairs: added percentage of daily volume compared to weekly volume
> Implemented basic search on homepage

- Lexplorer/Pages/NFTDetail.razor
- Shared/Helpers/GraphQLFragments.cs
- Shared/Services/LoopringGraphQLService.cs
- Shared/Services/NftMetadataService.cs
- xUnitTests/LoopringGraphTests/BaseLGTest.cs
- xUnitTests/NFTMetaDataTests/BaseNMDTests.cs
- xUnitTests/NFTMetaDataTests/TestNFTMetaData.cs
- xUnitTests/xUnitTests.csproj
Most important is reducing the humongous 100s RestRequest timeout when retrieving NFT metadata as that fails quiet often.
For all else, see the separate compact commits.
> NFT improvements

- Lexplorer/Pages/Account.razor
- Shared/Models/LoopringV3.cs
- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/TestAccount.cs
Added tabs to switch between balances and NFTs. 
Separate page number for NFTs.
Using that you can see some quite surprising things, e.g. with account 32933. Seems some LH are not as unique as others? Strangely enough, the official explorer does not shown these NFTs, but the graph certainly delivers these. You can also see that some have been minted several times, so it all makes sense - but yet they're hidden on the official accounts page.
> Added NFTs to accounts page fixing #70

- Lexplorer/Pages/NFTDetail.razor
- Shared/Models/NftMetadata.cs
this adds video support for nfts that define an animation_url in their metadata.json, nft with video example i used was 18497-5
On official explorer:
https://explorer.loopring.io/nft/0xc2bb4b516839df106fc4df8be868da5487638db9-0-0x27fa15862d7ebb1b8c8998a08b3405e12dc612ce-0x4de8f2002b80be98ccab8746c6569850a36b9f5de85b2900f846fa6134bfc8b7-10
if the animation url and image url are the same it will only display the image, otherwise if the animation url is not null and differs it will show the video.
> added video support

- Lexplorer/Pages/NFTDetail.razor
i found a little issue where somehow there is no metadata.json file for some nfts and it would throw a null reference exception when trying to get the content type. example nft tx-id [17895-113](https://lexplorer.io/nfts/0x1a3d0d183675491f3ac6ed53526013681290690c-0-0x5e6f93906fda5e308def4fcacea5a30d140e7166-0x70c85ec58c4aeba21bd4fb00799f8b1313a32a1e8e4784e37ad6d030dbe2eda5-0). im thinking the nft data was unpinned from pinata for this to happen.
this fix just adds an extra check to make sure the nft metadata is not null
heres what the same nft looks like on the official explorer
https://explorer.loopring.io/nft/0x1a3d0d183675491f3ac6ed53526013681290690c-0-0x5e6f93906fda5e308def4fcacea5a30d140e7166-0x70c85ec58c4aeba21bd4fb00799f8b1313a32a1e8e4784e37ad6d030dbe2eda5-0
> fix for null metadata error on some nfts

- Lexplorer/Components/NFTContent.razor
- xUnitTests/NFTMetaDataTests/TestNFTMetaData.cs
fix #88 . this adds html support in animation url via an iframe. security wise i copied the same attributes of the iframe that opensea uses, so i think they know what they are doing in terms of that. also added a unit test for the html content type. 
test nft id here: 0x574e9ca4605e4ebff1d4e9b204b16fe73f122f82c60da0186af3ded68bff9c10
i would ideally like to autosize the height of the iframe to match the height of the body in the iframe but i couldnt figure out that out for now. if
> add html animation in url support

- .github/workflows/dev_lexplorer(dev).yml
- Lexplorer/Shared/MainLayout.razor
- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/TestSearch.cs
if searching by nft id that was all uppercase it wouldn't return anything in the results. similar issue when checking for ens, i've just made the conditional to lower so it matches the .eth portion. i didn't realise in azure that i have an additional deployment slot so ive set it up to deploy a development site at https://lexplorer-dev.azurewebsites.net on push/merge to this branch.
going forward should this be the main branch we develop on then? if we are happy with the changes on the development site we merge this branch into master/production?
> fix for search when it contains only uppercase. 

- Lexplorer/Pages/Account.razor
- Shared/Services/LoopringGraphQLService.cs
- Shared/Services/NftMetadataService.cs
This one was actually quite complex and it hopefully solves #87 
The commit message of the 2nd commit explains all the important details, which I copied here for easier reading:
* cts property on the page object, but initially null
* each call of OnParametersSetAsync cancels and disposes any existing cancellation token before creating a new one - this ensures that unfinished previous calls will cancel
* it stores the current cts in a local copy to avoid that it inadvertently uses the new cts of a future call
* surround the whole method and catch only OperationCanceledException!
* add a IDisposable implementation and cancel and dispose cts
* all of this still hadn't solved the duplicate NFTdata entries!
* similar to the localCTS above, we now have a localNFTData too
* it is used for the …
> Add cancellation token support

- Lexplorer/Helpers/LAppCacheExtension.cs
- Lexplorer/Pages/Account.razor
- Lexplorer/Pages/NFTDetail.razor
* check for empty NFTSlots was wrong
* luckily I found a way to avoid manual disposing
* now "using" the localCTS
* initially setting page cts to localCTS, so subsequent call will cancel us
* before using is finished, make an interlocked exchange for cts back to null, so it's not cancelling our already disposed cts with the next call
* also added a universal exception catch which writes other exceptions to the trace - ideally, at least under the dev environment, it should show the trace in the browser; had a quick look: search term to look for is "ErrorBoundary"
> Fixing #96: empty NFTSlots check and additional exception to be caught

- Lexplorer/Pages/NFTDetail.razor
- Shared/Models/NftMetadata.cs
this PR is to display traits on the nft details page if they have been defined in the metadata. example NFT ID: 0x34ba0414a5fe091fd624469b02fb9e77cc33dffd7f71e897c4c948498568056c    , this is one from the GME Marketplace. Another NFT from a popular collection on Discord, 0x5e6de510d95b30c17d33c2659d0ac571dcf6a0e5a1e83fc0788b9e1b23507360
> added traits to nft details page

- Lexplorer/Components/HomepageOverview.razor
- Lexplorer/Pages/Account.razor
- Lexplorer/Pages/BlockDetails.razor
- Lexplorer/Pages/NFTDetail.razor
- Lexplorer/Pages/NFTOverview.razor
- Lexplorer/Pages/PairsOverview.razor
- Lexplorer/Pages/TransactionDetail.razor
- Lexplorer/Pages/TransactionsOverview.razor
- Shared/Services/EthereumService.cs
- Shared/Services/LoopringGraphQLService.cs
- Shared/Services/NftMetadataService.cs
- xUnitTests/NFTMetaDataTests/TestNFTMetaData.cs
This became quite a loose collection of smaller and bigger improvements.
After PR #99 I cleaned up MetaData URL handling. The redirection of ipfs:// links via piñata is now done at the latest possible moment, when downloading the meta data. The RestClient now longer has a baseURL (even though it did indeed work requesting other URLs).
I didn't include the code I tried for #85 simply because I'm not sure this is actually improving things.
I See that you reverted the test for the NFT model content type - I've actually extended it here, so it accepts both. Strangely enough, even if my GitHub action runs on Linux, it got the correct content type. So anyways, just as a warning: this might create a conflict once you merge this to master.
> Various NFT improvements

- Lexplorer/Pages/BlockDetails.razor
- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/TestTransaction.cs
* as described in #50 - the non-hosted graphs don't like unused query parameters
* removed block from query completely, was never used
* if no typename is provided, delete the lines in the query
* added new tests for GetTransactions
> Fix Invalid query error when using non-hosted graph

- Lexplorer/Pages/Account.razor
* Added MudChip to show balance of NFTs
* Set name of NFT to H6 instead of H5 for readability
(I hope this is done the correct way now)
| Desktop | Mobile |
|----------|---------|
|![image](https://user-images.githubusercontent.com/58626043/165920968-31192cc4-fb2d-427d-8bbb-c2434b111277.png)|![image](https://user-images.githubusercontent.com/58626043/165921134-67b982d0-843b-46e1-b19d-4ec398d9ff30.png)|
> Feature: Nft balance chip

- Lexplorer/Pages/_Host.cshtml
- Lexplorer/Shared/MainLayout.razor
Back when I made #102 I left DarkMode off by default, because I was hoping to have it a) correctly enabled depending on users settings and b) have it persistent for users across sessions.
Both are covered in https://jonhilton.net/blazor-tailwind-dark-mode-local-storage/ but I'm only going for the initial setting for now.
Will keep it as a draft for now, but could already be merged if desired.
> Automatically start in DarkMode if user has this enabled locally

- Shared/Models/LoopringV3.cs
With my last merge the action had a failed test in GetPools - because it returned null. Upon debugging I saw the JSON conversion failed because pool id 114 has feeBipsAMM = null. This bug can also be seen in production if you go to the Accounts page and filter by Pool - the page will remain empty.
Fix is to make the field nullable.
> Fix GetPools where pool id 114 has feeBipsAMM = null

- Lexplorer.sln
- Lexplorer/Dialogs/SearchDialog.razor
- Lexplorer/Shared/MainLayout.razor
- Lexplorer/_Imports.razor
Closes #127 
* Added SearchDialog with textfield and search button
* Updated mainlayout to show searchfield on larger devices and hide on smaller.
* Updated mainlayout to show iconbutton on small devices and hide on large which triggers dialog
* Searchterm from dialog gets sent as dialog result and sets searchTerm if not null. 
| Large device | Small device |
|---------------|---------------|
| ![image](https://user-images.githubusercontent.com/58626043/166142267-2a8910c5-7af1-4ba8-9b59-adaffb27e682.png) | ![image](https://user-images.githubusercontent.com/58626043/166142341-15d47724-c883-49f8-be0d-06eb3376b733.png) |
> Feature: search dialog on small devices

- Lexplorer/Dialogs/SearchDialog.razor
- Lexplorer/Shared/MainLayout.razor
Closes #129 
* Fixed icon color on light mode
* Dialog search can now be triggered multiple ways; pressing enter, clicking adornment or clicking search button
* Added autofocus to searchfield
* Added close button
Light mode icon:  
Dialog opened:
> Fix: search dialog fixes

- Lexplorer/Components/HomepageOverview.razor
- Lexplorer/Components/L1AccountLink.razor
- Lexplorer/Components/L1TransactionLink.razor
- Lexplorer/Components/NFTContent.razor
- Lexplorer/Helpers/LinkHelper.cs
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/BlockDetails.razor
- Lexplorer/Pages/BlocksOverview.razor
- Lexplorer/Pages/NFTDetail.razor
- Lexplorer/Pages/NFTOverview.razor
- Lexplorer/Pages/PairsOverview.razor
- Lexplorer/Pages/TransactionsOverview.razor
- Lexplorer/Shared/MainLayout.razor
- Lexplorer/Shared/NavMenu.razor
- Shared/Helpers/TimestampConverter.cs
- Shared/Helpers/TokenAmountConverter.cs
- Shared/Models/LoopringV3.cs
- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/HelperTests/TestTokenAmountConverter.cs
- xUnitTests/LoopringGraphTests/TestAccountTransactions.cs
- xUnitTests/LoopringGraphTests/TestBlock.cs
- xUnitTests/LoopringGraphTests/TestNFT.cs
- xUnitTests/LoopringGraphTests/TestPairs.cs
- xUnitTests/LoopringGraphTests/TestSearch.cs
- xUnitTests/LoopringGraphTests/TestTransaction.cs
* For consistency changed all String, Int32, Int64, Boolean value types and invokaction of methods from classes to c# aliases. 
Some places string was used, other places String was used. Now it's consistent use as of the c# standards.
Tested OK, no functionality has been compromised
> Fix: dotnet value types lower case

- Lexplorer/Dialogs/SearchDialog.razor
* the property setter was added to make pressing Enter also search
* this resulted in a crash when starting the search with clicking the
button or adornment icon, probably because that involved a focus
change which itself invoked the property setter too
* it also made it impossible to cancel, because clicking the close
button also invoked the property setter
* solution
* no explicit property setter anymore
* instead assign OnKeyDown event and call DoDialogSearch from there
if the key is Enter or NumpadEnter
* for this to work, the MudTextField needs Immediate=true so the
bound property is always up to date
> Fix #134 SearchDialog crash

- Lexplorer/Pages/AccountDetails.razor
* so user can always go back if somehow ended up on an empty page
* fixes #138
To reproduce with any account (not necessarily if NFTCount is multiple of NFTPageSize): edit URL to go beyond end of NFTs.
Previously: pagers was hidden and "No NFTs" displaced
Now: pager still visible even though no NFTs are shown
> Fix #138 hide NFT pager only if on page 1

- Lexplorer/Components/NFTContent.razor
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/BlockDetails.razor
- Lexplorer/Pages/NFTDetail.razor
- Lexplorer/Pages/PairsDetail.razor
- Lexplorer/Pages/TransactionDetail.razor
- Lexplorer/wwwroot/app.css
Closes #145
* NFT Title not showing correctly on smaller devices
* Added new css classes for usage on nft types showing
* NFT's now displaying at a set heigth and width of 100% for smaller devices. (iFrame nfts not perfectly enhanced)
> Fix: NFT title and div small devices

- Lexplorer/Components/HomepageOverview.razor
- Lexplorer/Components/PairsTableDetails.razor
- Lexplorer/Pages/PairsOverview.razor
- Shared/Services/LoopringGraphQLService.cs
* no longer query yesterday versus currently running week, i.e. no longer skip 1 when querying daily data as described in #151 
* remove volume percentage as calculation didn't make sense considering both 7D and 24H volume are still being filled up
> Fix Pairs overview table #151

- Lexplorer/Pages/NFTDetail.razor
- Lexplorer/Pages/TransactionDetail.razor
- Shared/Models/LoopringV3.cs
* took meaning 0 = ERC1155 and 1 = ERC721 from readme in
LoopmintSharp
* new row in NFTDetail
* updated in transaction details showing type name instead of type
> Add NFT type name instead of just the number

- Lexplorer/Components/NFTContent.razor
@fudgebucket27 this should fix issue #108. The problem was not related to allowing sound but good ol' CORS.. 🤞
Console error from the example NFT in #108:
`Access to XMLHttpRequest at 'https://fudgey.mypinata.cloud/ipfs/QmX5Bxv77TPDwMH4k3vfrB8KnwWbVP43fP9Pa4EzGLi92Y/sounds/hoowav.mp3?1650209195009' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`
> Fix #108 allow sound for html NFTs

- Lexplorer/wwwroot/app.css
* tried with height: auto first, but what's the actual point compared
to omitting height completely?
* only happened with Safari because the img was in a table
* now removing height all-together, for smaller size devices too
> Fixing #153 with skewed images in Safari (macOS and iOS)

- Lexplorer/Components/NFTContent.razor
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/NFTDetail.razor
- Lexplorer/appsettings.json
- Shared/Models/NftMetadata.cs
- Shared/Services/NftMetadataService.cs
- xUnitTests/NFTMetaDataTests/BaseNMDTests.cs
* get _ipfsBaseUrl from config - similar to LoopStat service
* refactored MakeIPFSLink so it's publicly availabe
* removed URL helper properties from NFTMetaData
* updated all sites where these properties were used to use the
services MakeIPFSLink method
* for tests just use a hardcoded URL with overloaded constructor to
directly provide the base URL
> Fix #160 change IPFS links to loopring pinata

- Lexplorer/Pages/AccountDetails.razor
* happens, when URL nftPageNumber is edited to go beyond end
* make accountNFTSlots non-nullable and handle cases to avoid they
become null
* minor change remove unnecessary ! when calling GetAccountTotalNfts
> Fix crash when somehow we end up on a NFTPage with no slots

- Lexplorer/appsettings.json
- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/BaseLGTest.cs
* Similar to what has already been done for NFT and Loopstats services
> Making Loopring graph endpoint configurable via appsettings

- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/TestSearch.cs
* test BigInteger.TryParse first and if it succeeds then
convert to hexadecimal string
* needs leading zeros removed for the graph to find it (no clue why
.NET even adds them)
* added test cases
* decimal notation requires that "contains" check is made optional
* fixes #173
> Support searching for NFT with decimal BigInteger

- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/TestSearch.cs
Fixes #183 
* graph returned error if BigInteger was parsed, but contained an
odd number of bytes
* added new test case
* stripping leading zeros has to stay in there, as searching with
2 leading zeros won't work (NFT test case failed)
* move old RegEx comment to where the code is now
> Fix search errors

- Lexplorer/Pages/PairsDetail.razor
- Lexplorer/Shared/MainLayout.razor
Fix #176 by naming the CascadingValue for isDarkMode properly. 
Requires CascadingParameter property in PairsDetail to be named too.
> Fix mixed up pagination icons in dark mode

- Lexplorer/Components/TransactionTableDetails.razor
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/PairsDetail.razor
- Lexplorer/Pages/TransactionDetail.razor
- Lexplorer/Program.cs
- Shared/Models/LoopringPoolToken.cs
- Shared/Services/LoopringGraphQLService.cs
- Shared/Services/LoopringPoolTokenCacheService.cs
- Shared/Shared.projitems
- xUnitTests/LoopringGraphTests/TestRemoveWithTokenID.cs
- xUnitTests/LoopringGraphTests/TestSwapPairAndPool.cs
This tackles the long outstanding #63 without using the Loopring API but with some graphQL trickery:
1. It builds its own never expiring cache (since the information cannot change really).
2. It has to make some assumptions (e.g. decimal places of pool tokens) but AFAICS these should all be okay.
3. Some of this - but not everything - would have been easier with the token list from the Loopring API (and of course with an improved graph none of this would have been necessary), but I am actually quite fine with the way this turned out.
@fudgebucket27 and @danielsolistensvik I'd love to hear your take on this!
> Pools and pairs and pool token support

- Lexplorer/Dialogs/NFTMetadataDialog.razor
- Lexplorer/Pages/NFTDetail.razor
- Shared/Models/NftMetadata.cs
- Shared/Services/NftMetadataService.cs
Closes #190 
* added JSONContent to NftMetadata class
* MetadataService takes detour via JToken to beautify the .json and
store it with the deserialized object
* NFT detail page shows additional button next to View collection
* button shows new dialog, just with a readonly text editor
> New View JSON button on NFT details page

- Lexplorer/Components/NFTGrid.razor
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/NFTCollection.razor
Closes #193 
Wow, that has been quite a ride, lots of new things learnt, but I think I got everything! Cancellation etc. work, directly changing page numbers via the URL etc. all still seem to work just fine!
No visual changes AFAICS.
The grid needs to have a list of `AccountNFTSlot`, not `NonFungibleToken`, for it to display the balance - when viewing on AccountDetails. For the collection view, a LINQ transformation of the list is therefore necessary, but I don't think that'll hurt.
Please give it a thorough test drive on dev.
Now that this is separated out, we can tackle #180
> Separated NFT grid

- Shared/Helpers/GraphQLTransactionListFragments.cs
- Shared/Services/LoopringGraphQLService.cs
- Shared/Shared.projitems
As planned in #177
* using new separate fragments to avoid interference with other detailed queries where fragments might need to contain more
* removed everything from both transactions queries that seemed unused (most notably data - not needed for transaction *list*)
> Speed up transactions query

- Lexplorer/Components/NFTGrid.razor
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/NFTCollection.razor
Follow-up for #195 after discovering several issue
* remove unused PageSize parameter
* follow top-down parameter rule, a component should never change
it's own parameters, that is always the task of the parent
* use _internalPage for binding to MudPagination
* that way we can make it happy, by setting it directly in gotoPage
to avoid it switching back and forth
* we need PageNumber *and* the NFTSlots to reliably load the metadata
* but any and each parameter change will tricker OnParameterSetAsync
* to determine when we're actually ready to load a new NFTdata
collection we need to store for what page and slots we loaded last
* this requires that AccountDetails and NFTCollection pages never
use empty NFTSlots as intermediary, because the NFTGrid has no
way of knowing whether this is the …
> Several fixes for misbehaving NFTGrid

- Lexplorer/Components/NFTGrid.razor
Fixes #199
* locally defines the style since only used here for now
From what I understand, we should be safe to use [`-webkit-line-clamp`](https://caniuse.com/?search=-webkit-line-clamp).
Screenshot on macOS with Safari:
Same NFT on mobile fits into 3 lines, so it isn't cropped:
> Crop NFT description after 3 lines

- Lexplorer/Components/LexpansionPanel.razor
- Lexplorer/Components/NFTGrid.razor
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/NFTDetail.razor
Closes #202 
* Changed from Tabs to Expansion Panels in AccountsDetail and NFTDetails pages
* Small update to NFTGrid pagination so it better fits the panels
> Move from Tabs to Expansions Panels

- Lexplorer/Components/NFTGrid.razor
- Lexplorer/Pages/NFTCollection.razor
- Shared/Models/NftMetadata.cs
- Shared/Services/NftMetadataService.cs
Closes #203 
If metadata is present, shows it similar to NFT details, including thumbnail preview and view metadata button:
* refactored NFTGrid so LoadMetaData can be called
* not moved to a service, since we want app cache usage
* added collection details to page if present - identical to NFT
detail page where possible
* showing image of thumbnail_uri
* added View Metadata button too
* simple GetCollectionMetadata - no ipfs link handling etc. for now
> Show NFT collection meta data

- Lexplorer/Components/NFTGrid.razor
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/AccountsOverview.razor
- Lexplorer/Pages/BlockDetails.razor
- Lexplorer/Pages/NFTCollection.razor
- Lexplorer/Pages/NFTDetail.razor
As reported in #209
* added finally block to all relevant places so cts will always be reset to null
* in NFTGrid no longer dispose the cts - as it's not owned by the grid itself
* use Interlock.Exchange when initially setting cts too, just for consistency
* fixed catches null exception when nftGrid reference was not yet set by making it's method static and passing in all relevant services
> Fix #209 Cancellation token disposed errors

- Shared/Models/NftMetadata.cs
- Shared/Services/NftMetadataService.cs
- xUnitTests/NFTMetaDataTests/TestNFTMetaData.cs
Fixes #210 
array syntax: `0x32f006a901505c8c015714cc4390f7f5447c1b07983b050c9cd92da90777584c`
dictionary syntax: `0x4af1532239111dd9ff37a69b0241581252a5728eb6a9b78095655413f3861e66`
* properties is now `JsonIgnore` and manually deserialised in a fail-safe way
* the alternative syntax (array of objects with "key" and "value" properties) is manually parsed
* refactored deserialisation and added tests for both variants
> Fix #210 alternative properties syntax

- Lexplorer/Components/OpenEndedPager.razor
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/AccountsOverview.razor
- Lexplorer/Pages/BlockDetails.razor
- Lexplorer/Pages/BlocksOverview.razor
- Lexplorer/Pages/NFTDetail.razor
- Lexplorer/Pages/NFTOverview.razor
- Lexplorer/Pages/PairsOverview.razor
- Lexplorer/Pages/TransactionsOverview.razor
As described in #119 
The component itself doesn't result in a different appearance.
But all the places now have an optional 2nd pager at the bottom (similar to NFTGrid as described in #150) when on smaller devices:
> #119 New open ended pager component

- Lexplorer/Components/HomepageOverview.razor
- Lexplorer/Helpers/LinkHelper.cs
- Lexplorer/Pages/BlockDetails.razor
- Lexplorer/Pages/BlocksOverview.razor
- Lexplorer/Pages/PairsOverview.razor
- Lexplorer/Pages/TransactionsOverview.razor
- Shared/Models/LoopringV3.cs
- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/TestBlock.cs
- xUnitTests/LoopringGraphTests/TestPairs.cs
- xUnitTests/LoopringGraphTests/TestSearch.cs
- xUnitTests/LoopringGraphTests/TestTransaction.cs
* removed several helper classes which were just made to match the JSON structure
* no longer necessary if accessing tokens like "data" directly before deserialisation
* renamed two helper classes with DTO suffix for GetBlockDetails and GetBlocks - the only two queries that retrieve the proxy in addition to the actual entities (Block and List<Block>)
* GetTransactions no longer retrieves proxy - wasn't used
* adapted all tests and pages/components to the new structure which helped reduce a lot of code and we're no closer to the graph entity names again
> Model cleanup

- Lexplorer/Components/NFTGrid.razor
Closes #223 
Screenshot with the fix applied (as opposed to the one in the issue):
> Fix #223 forcing break on lengthy NFT titles

- Lexplorer/Pages/TokenDetails.razor
- Shared/Helpers/TimestampConverter.cs
- Shared/Services/LoopringPoolTokenCacheService.cs
* token details page
* use failSafeSymbol in case symbol is empty so "Token {id}" is displayed
* show token address with link to etherscan to check the contract
* adapt pool token naming convention so they match that of the contracts
* i.e. name = AMM-x-y, symbol = LP-x-y
* refactored TimestampConverter.ToUTCTime() as suggested on discord
> Set of smaller token related improvements

- Shared/Models/LoopringV3.cs
- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/TestSearch.cs
Fixing  #222
* intentionally searching case insensitive and with contains
* added missing typename property to token, here it was only necessary
for the search results to list the proper search result type
* added basic test, for LRC specifically and eth for a whole set of
search results
> Searching for token symbol

- Lexplorer/Components/ENSList.razor
- Lexplorer/Pages/AccountDetails.razor
- Lexplorer/Pages/TokenDetails.razor
- Lexplorer/Program.cs
- Lexplorer/Shared/MainLayout.razor
- Lexplorer/appsettings.json
- Shared/Models/ENS.cs
- Shared/Services/ENSCacheService.cs
- Shared/Shared.projitems
- xUnitTests/ENSTests/BaseENSTests.cs
- xUnitTests/ENSTests/TestENSService.cs
- xUnitTests/xUnitTests.csproj
Closes #219 
1. Added to account details page
2. if a lookup is made during a search, the search term and the resulting address are added to the cache
3. reverse lookup is done using https://thegraph.com/hosted-service/subgraph/ensdomains/ens
4. since some *.loopring.eth ENS only store a hash instead of the labelName, they cannot be properly looked up in reverse
5. this might result in the same ENS appearing twice - hence the icons depicting the origin of the ENS: <img width="943" alt="image" src="https://user-images.githubusercontent.com/44807458/181470709-ea270e42-f52b-476f-8440-7c8579d184ab.png">
7. the correct ENS name here is only shown because I previously searched for it
8. with this approach, we're open for potentially adding the Loopring API as a 3rd source for ENS lookups
9. …
> New ENSCacheService for ENS lookup and reverse lookup

- Shared/Services/NftMetadataService.cs
Closes #235 
* L1 ERC721 contract 0x26fD3e176c260e7fef019966622419DabfebB299
has an extra ipfs/ prefix in the uri
* handle that in MakeIPFSLink as an additional ipfs:// prefix which
is replaced with the pinata base URL
> CyberCrew NFT contract uri bug workaround

- xUnitTests/NFTMetaDataTests/TestNFTMetaData.cs
previous audio test was timing out and causing build to fail. updated with new nft that doesnt time out
> fix audio test timing out with new test nft

- Lexplorer/Pages/NFTDetail.razor
- Shared/Services/NftMetadataService.cs
- xUnitTests/NFTMetaDataTests/TestNFTMetaData.cs
Fixes #242 
1. When adding exception message to NftMetaData.error, avoid adding the same error again and again. This is necessary because these errors are not cached so they will occur every time the page is loaded.
2. When escaping a IPFS URL - which needs escaping - unescape it first, then escape again. Fixes partially escaped URLs. This makes NFT `0x17a84412503e323fb35a378d04a3dd16be46632c7b98db52082f40e369f84e47` work again.
Now there's only one special case left which we cannot handle: a unescaped URL using % and numbers as if it would be escaped. But that couldn't really be fixed by anyone. And strictly speaking these are all mint errors.
> Fix NFT errors

- Shared/Services/NftMetadataService.cs
Fixes #248
* seen with a Loophead NFT, where the first request failed (timeout?)
so it added an extra wrong /metadata.json
* now never done if the URL already contains metadata.json
> Prevent metadata.json to be added twice to the URL

- Lexplorer/Pages/NFTDetail.razor
- Shared/Models/NftMetadata.cs
- Shared/Services/NftMetadataService.cs
This will help with debugging issues like #248 and it will probably be handy for others too.
All 3 URLs will link to the pinata gateway that we use. The MetaData URL shown is the original URL as returned from the contract, while the link will contain all the modifications that we might make (escaping, adding /metadata.json etc.)
> Store original meta data URL in NftMetadata and show it

- xUnitTests/NFTMetaDataTests/TestNFTMetaData.cs
1. Instead of one theory per content type, a single theory for all.
2. Instead of first fetching the MetaData URL and then the metadata, feed the theory directly with the animation_urls.
Especially the 2nd part might also make these tests fail less often, as only one IPFS fetch is required.
> Refactor nft content type tests

- Lexplorer/Pages/NFTDetail.razor
- Shared/Services/LoopringGraphQLService.cs
- Shared/Services/NFTHolderExportService.cs
Fixes #254
* ordering ascending by slot id
* instead of using skip, pass in last slot id and filter with id_gt
* sped up export by fetching 200 holders with each query instead of just 10
* remove nftID from csv rows (same for all!) but include account id instead
* add header section with helpful details about the NFT
* better export filename, using nftID instead of .id and more compact UTC timestamp
> Fix NFT holder export skip limit

- Shared/Services/LoopringGraphQLService.cs
- Shared/Services/TransactionExportDefaultCSVFormat.cs
- Shared/Services/TransactionExportService.cs
- xUnitTests/LoopringGraphTests/TestAccountTransactions.cs
Fixes #254 
* similar approach to what was done for NFT holder export in #255 
* instead of using skip and processed counter, use lastID and internalID filtering
* increased chunk size to 1000, so most people will probably only need one chunk :)
* tested with exporting a months worth of LRC/USDC pool (no. 108) transactions - almost 24k transactions in what felt like less than a minute
* also fixed empty lines in exports for ignored transaction (SignatureVerification, AmmUpdate)
> Fix transaction export skip limit

- Shared/Services/LoopringGraphQLService.cs
- xUnitTests/LoopringGraphTests/TestNFT.cs
* added address from bug report to test-case
* this is the official case-sensitive form of that contract address as seen on etherscan
* still, the graph will silently fail and just return an empty set
* converting token address to lowercase fixes graph
Fixes #263
> Convert collection token ID string to lowercase when querying graph

- Shared/Services/ENSCacheService.cs
- xUnitTests/ENSTests/TestENSService.cs
* instead of querying accounts with id, query domains with resolvedAddress_in
* e.g. loopring.itsmonty.eth showed on the address for itsmonty.eth
* now we're actually querying the resolved address that we're interested in
* causes ReverseLookup to return a list of domains instead of accounts
* in ReverseLookupAddressList add each domain separately as they're no longer grouped by account
Fixes #264
Account 34247 with fixed ENS query:
> Restructured ENS graph query
